import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import * as fal from "npm:@fal-ai/serverless-client";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface FalImage {
  url: string;
  width: number;
  height: number;
  content_type: string;
}

interface FalResult {
  images: FalImage[];
}

// Sanitize folder name: remove accents and special characters
function sanitizeFolderName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove diacritics
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, ''); // Only allow alphanumeric and hyphens
}

// Upload image from URL to Supabase Storage
async function uploadToStorage(
  imageUrl: string,
  supabase: any,
  bucket: string,
  fileName: string
): Promise<string> {
  try {
    console.log('Downloading image from Fal.ai:', imageUrl);
    const imageResponse = await fetch(imageUrl);
    if (!imageResponse.ok) {
      throw new Error(`Failed to download image: ${imageResponse.status}`);
    }
    
    const imageBlob = await imageResponse.blob();
    const arrayBuffer = await imageBlob.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    
    console.log('Uploading to storage:', fileName);
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from(bucket)
      .upload(fileName, uint8Array, {
        contentType: 'image/png',
        cacheControl: '31536000', // 1 year cache
        upsert: true
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      throw new Error(`Failed to upload image: ${uploadError.message}`);
    }

    const { data: urlData } = supabase.storage
      .from(bucket)
      .getPublicUrl(fileName);

    console.log('Image uploaded successfully:', urlData.publicUrl);
    return urlData.publicUrl;
  } catch (error) {
    console.error('Error in uploadToStorage:', error);
    throw error;
  }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      location_page_id,
      city_name, 
      city_slug,
      topic_slug,
      intent_type,
      image_prompt,
      regenerate = false
    } = await req.json();

    if (!city_name || !topic_slug) {
      return new Response(
        JSON.stringify({ error: 'city_name and topic_slug are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const FAL_KEY = Deno.env.get('FAL_KEY');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!FAL_KEY) {
      throw new Error('FAL_KEY is not configured');
    }
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Supabase configuration is missing');
    }

    // Configure Fal.ai
    fal.config({ credentials: FAL_KEY.trim() });

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Build location-specific image prompt
    const defaultPrompt = `Professional aerial photography of ${city_name}, Costa del Sol, Spain. 
Mediterranean coastline with azure waters, luxury villas and apartments, 
Spanish architecture, palm trees, golden beaches. 
Ultra high resolution, real estate marketing style, 
warm Mediterranean sunlight, no text overlays.`;

    const finalPrompt = image_prompt 
      ? `${image_prompt}. Ultra high resolution.`
      : defaultPrompt;

    console.log('Generating location image for:', city_name, topic_slug);
    console.log('Using prompt:', finalPrompt);

    // Generate image using Fal.ai Nano Banana Pro
    const result = await fal.subscribe("fal-ai/nano-banana-pro", {
      input: {
        prompt: finalPrompt,
        aspect_ratio: "16:9",
        resolution: "2K",
        num_images: 1,
        output_format: "png"
      },
      logs: true,
    }) as FalResult;

    if (!result.images || result.images.length === 0) {
      throw new Error('No images generated by Fal.ai');
    }

    const generatedImage = result.images[0];
    console.log('Image generated successfully:', generatedImage.url);

    // Generate unique filename with sanitized folder name
    const timestamp = Date.now();
    const sanitizedCitySlug = sanitizeFolderName(city_slug || city_name);
    const sanitizedTopicSlug = sanitizeFolderName(topic_slug);
    const fileName = `${sanitizedCitySlug}/${sanitizedTopicSlug}-${timestamp}.png`;

    // Upload to Supabase storage
    const publicUrl = await uploadToStorage(
      generatedImage.url,
      supabase,
      'location-images',
      fileName
    );

    // Generate SEO-optimized alt text and caption
    const altText = `Aerial view of ${city_name}, Costa del Sol showing Mediterranean coastline, luxury properties, and ${intent_type?.replace(/-/g, ' ') || 'real estate'} opportunities`;
    
    const caption = `${city_name}, Costa del Sol - Premium real estate destination featuring stunning Mediterranean views, world-class amenities, and exceptional investment opportunities in Southern Spain.`;

    // If location_page_id is provided, update the database
    if (location_page_id) {
      const { error: updateError } = await supabase
        .from('location_pages')
        .update({
          featured_image_url: publicUrl,
          featured_image_alt: altText,
          featured_image_caption: caption,
          featured_image_width: generatedImage.width || 1920,
          featured_image_height: generatedImage.height || 1080,
          updated_at: new Date().toISOString()
        })
        .eq('id', location_page_id);

      if (updateError) {
        console.error('Failed to update location page:', updateError);
        // Don't throw - image was still generated successfully
      } else {
        console.log('Location page updated with new image');
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        image: {
          url: publicUrl,
          alt: altText,
          caption: caption,
          width: generatedImage.width || 1920,
          height: generatedImage.height || 1080,
          format: 'png',
          fileName
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-location-image:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
