-- Import 750 High-Authority Approved Domains (Fixed Tier Constraint)
-- All tourism/local government domains changed from tier_4 to tier_3

INSERT INTO public.approved_domains (domain, language, category, tier, trust_score, is_allowed, region, source_type, notes)
VALUES
  -- SPAIN
  ('lamoncloa.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish PM Office'),
  ('administracion.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Public Administration'),
  ('sede.administracion.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Admin Portal'),
  ('exteriores.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Foreign Affairs'),
  ('miteco.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Environment Ministry'),
  ('hacienda.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Treasury'),
  ('mitma.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Transport Ministry'),
  ('seg-social.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Social Security'),
  ('aeat.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Tax Agency'),
  ('ine.es', 'es', 'Statistics', 'tier_1', 100, true, 'ES', 'official', 'Spanish National Statistics'),
  ('dgt.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Traffic Authority'),
  ('policia.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish National Police'),
  ('guardiacivil.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Civil Guard'),
  ('inclusion.gob.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Social Inclusion Ministry'),
  ('mscbs.gob.es', 'es', 'Health', 'tier_1', 100, true, 'ES', 'official', 'Spanish Health Ministry'),
  ('juntadeandalucia.es', 'es', 'Local Government', 'tier_1', 100, true, 'ES-AN', 'official', 'Andalusian Regional Government'),
  ('turismoandaluz.com', 'es', 'Tourism', 'tier_3', 85, true, 'ES-AN', 'tourism_board', 'Andalusia Tourism Board'),
  ('andalucia.org', 'es', 'Local Government', 'tier_1', 100, true, 'ES-AN', 'official', 'Andalusia Official Portal'),
  ('malaga.eu', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Malaga City Council'),
  ('diputacionmalaga.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'provincial', 'Malaga Provincial Council'),
  ('marbella.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Marbella City Council'),
  ('benalmadena.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Benalmadena City Council'),
  ('mijas.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Mijas City Council'),
  ('fuengirola.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Fuengirola City Council'),
  ('torremolinos.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Torremolinos City Council'),
  ('estepona.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN-MA', 'municipal', 'Estepona City Council'),
  ('spain.info', 'es', 'Tourism', 'tier_3', 85, true, 'ES', 'tourism_board', 'Spain Tourism Official Site'),
  ('boe.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Official State Gazette'),
  ('aemet.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Meteorology Agency'),
  ('rtve.es', 'es', 'Media - National', 'tier_3', 90, true, 'ES', 'media', 'Spanish Public Broadcasting'),
  ('canalsur.es', 'es', 'Media - National', 'tier_3', 90, true, 'ES-AN', 'media', 'Andalusian Public TV'),
  ('elconfidencial.com', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'El Confidencial Digital'),
  ('abc.es', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'ABC Newspaper'),
  ('elmundo.es', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'El Mundo Newspaper'),
  ('elpais.com', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'El País Newspaper'),
  ('lavanguardia.com', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'La Vanguardia Newspaper'),
  ('20minutos.es', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', '20 Minutos News'),
  ('diariosur.es', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES-AN-MA', 'media', 'Diario Sur Málaga'),
  ('expansion.com', 'es', 'Media - Business', 'tier_3', 90, true, 'ES', 'media', 'Expansión Business News'),
  ('cinconoticias.com', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'Cinco Noticias'),
  ('marca.com', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'Marca Sports News'),
  ('efe.com', 'es', 'Media - National', 'tier_3', 90, true, 'ES', 'media', 'EFE News Agency'),
  ('consumer.es', 'es', 'Media - Quality Press', 'tier_3', 90, true, 'ES', 'media', 'Consumer Reports Spain'),
  ('ocu.org', 'es', 'Consumer Organization', 'tier_3', 85, true, 'ES', 'nonprofit', 'Spanish Consumer Organization'),
  ('sevilla.org', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN', 'municipal', 'Seville City Council'),
  ('granada.org', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN', 'municipal', 'Granada City Council'),
  ('cadiz.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN', 'municipal', 'Cádiz City Council'),
  ('cordoba.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES-AN', 'municipal', 'Córdoba City Council'),
  ('valencia.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES', 'municipal', 'Valencia City Council'),
  ('murcia.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES', 'municipal', 'Murcia City Council'),
  ('zaragoza.es', 'es', 'Local Government', 'tier_3', 85, true, 'ES', 'municipal', 'Zaragoza City Council'),
  ('barcelona.cat', 'es', 'Local Government', 'tier_3', 85, true, 'ES', 'municipal', 'Barcelona City Council'),
  ('ugt.es', 'es', 'Labor Organization', 'tier_3', 85, true, 'ES', 'nonprofit', 'Spanish General Workers Union'),
  ('ccoo.es', 'es', 'Labor Organization', 'tier_3', 85, true, 'ES', 'nonprofit', 'Spanish Workers Commissions'),
  ('unir.net', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'International University of La Rioja'),
  ('uam.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'Autonomous University of Madrid'),
  ('ugr.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN', 'academic', 'University of Granada'),
  ('uco.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN', 'academic', 'University of Córdoba'),
  ('uma.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN-MA', 'academic', 'University of Málaga'),
  ('ujaen.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN', 'academic', 'University of Jaén'),
  ('uca.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN', 'academic', 'University of Cádiz'),
  ('ucm.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'Complutense University of Madrid'),
  ('uned.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'National Distance Education University'),
  ('upm.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'Polytechnic University of Madrid'),
  ('us.es', 'es', 'Universities', 'tier_2', 95, true, 'ES-AN', 'academic', 'University of Seville'),
  ('uva.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'University of Valladolid'),
  ('universia.es', 'es', 'Universities', 'tier_2', 95, true, 'ES', 'academic', 'Spanish University Network'),
  ('cultura.gob.es', 'es', 'Culture', 'tier_1', 100, true, 'ES', 'official', 'Spanish Culture Ministry'),
  ('agenciatributaria.es', 'es', 'Government', 'tier_1', 100, true, 'ES', 'official', 'Spanish Tax Agency'),
  ('omsida.org', 'es', 'Health', 'tier_3', 85, true, 'ES', 'nonprofit', 'Spanish AIDS Organization'),
  ('fundacionbancaria.org', 'es', 'Nonprofit', 'tier_3', 85, true, 'ES', 'nonprofit', 'Spanish Banking Foundation'),
  ('fundaciononce.es', 'es', 'Nonprofit', 'tier_3', 85, true, 'ES', 'nonprofit', 'ONCE Foundation'),
  ('fundacioncarolina.es', 'es', 'Nonprofit', 'tier_3', 85, true, 'ES', 'nonprofit', 'Carolina Foundation'),
  ('fundacionmapfre.org', 'es', 'Nonprofit', 'tier_3', 85, true, 'ES', 'nonprofit', 'Mapfre Foundation'),

  -- UK
  ('gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'UK Government'),
  ('ons.gov.uk', 'en', 'Statistics', 'tier_1', 100, true, 'GB', 'official', 'Office for National Statistics'),
  ('nhs.uk', 'en', 'Health', 'tier_1', 100, true, 'GB', 'official', 'National Health Service'),
  ('bbc.co.uk', 'en', 'Media - National', 'tier_3', 90, true, 'GB', 'media', 'British Broadcasting Corporation'),
  ('theguardian.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'GB', 'media', 'The Guardian'),
  ('independent.co.uk', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'GB', 'media', 'The Independent'),
  ('standard.co.uk', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'GB', 'media', 'Evening Standard'),
  ('nationalarchives.gov.uk', 'en', 'Culture', 'tier_1', 100, true, 'GB', 'official', 'UK National Archives'),
  ('historicengland.org.uk', 'en', 'Culture', 'tier_3', 85, true, 'GB', 'nonprofit', 'Historic England'),
  ('food.gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'Food Standards Agency'),
  ('visitbritain.com', 'en', 'Tourism', 'tier_3', 85, true, 'GB', 'tourism_board', 'Visit Britain Tourism'),
  ('visitengland.com', 'en', 'Tourism', 'tier_3', 85, true, 'GB', 'tourism_board', 'Visit England Tourism'),
  ('statista.com', 'global', 'Statistics', 'tier_2', 95, true, 'GLOBAL', 'data', 'Statista Statistics Portal'),
  ('nature.com', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'Nature Publishing'),
  ('royalsociety.org', 'en', 'Research', 'tier_2', 95, true, 'GB', 'academic', 'Royal Society'),
  ('metoffice.gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'UK Meteorological Office'),
  ('fsa.gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'Financial Services Authority'),
  ('defra.gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'Environment, Food & Rural Affairs'),
  ('education.gov.uk', 'en', 'Government', 'tier_1', 100, true, 'GB', 'official', 'Department for Education'),
  ('london.gov.uk', 'en', 'Local Government', 'tier_3', 85, true, 'GB', 'municipal', 'Greater London Authority'),
  ('scotland.org', 'en', 'Local Government', 'tier_1', 100, true, 'GB-SCT', 'official', 'Scottish Government'),
  ('britannica.com', 'en', 'Reference', 'tier_3', 90, true, 'GB', 'reference', 'Encyclopaedia Britannica'),
  ('economist.com', 'en', 'Media - Business', 'tier_3', 90, true, 'GB', 'media', 'The Economist'),
  ('reuters.com', 'en', 'Media - National', 'tier_3', 90, true, 'GB', 'media', 'Reuters News Agency'),
  ('ft.com', 'en', 'Media - Business', 'tier_3', 90, true, 'GB', 'media', 'Financial Times'),
  ('tandfonline.com', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'Taylor & Francis Online'),
  ('sagepub.com', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'Sage Publications'),
  ('ucl.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'University College London'),
  ('ox.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'University of Oxford'),
  ('cam.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'University of Cambridge'),
  ('lshtm.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'London School of Hygiene & Tropical Medicine'),
  ('manchester.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'University of Manchester'),
  ('warwick.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'University of Warwick'),
  ('kcl.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'Kings College London'),
  ('swansea.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'Swansea University'),
  ('researchgate.net', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'ResearchGate Platform'),
  ('open.ac.uk', 'en', 'Universities', 'tier_2', 95, true, 'GB', 'academic', 'Open University'),
  ('ukri.org', 'en', 'Research', 'tier_2', 95, true, 'GB', 'official', 'UK Research and Innovation'),

  -- USA
  ('usa.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'US Government Portal'),
  ('whitehouse.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'White House'),
  ('census.gov', 'en', 'Statistics', 'tier_1', 100, true, 'US', 'official', 'US Census Bureau'),
  ('cdc.gov', 'en', 'Health', 'tier_1', 100, true, 'US', 'official', 'Centers for Disease Control'),
  ('nih.gov', 'en', 'Health', 'tier_1', 100, true, 'US', 'official', 'National Institutes of Health'),
  ('fda.gov', 'en', 'Health', 'tier_1', 100, true, 'US', 'official', 'Food and Drug Administration'),
  ('noaa.gov', 'en', 'Environment', 'tier_1', 100, true, 'US', 'official', 'National Oceanic and Atmospheric Administration'),
  ('nasa.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'NASA'),
  ('epa.gov', 'en', 'Environment', 'tier_1', 100, true, 'US', 'official', 'Environmental Protection Agency'),
  ('doi.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'Department of the Interior'),
  ('dol.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'Department of Labor'),
  ('treasury.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'US Treasury'),
  ('irs.gov', 'en', 'Government', 'tier_1', 100, true, 'US', 'official', 'Internal Revenue Service'),
  ('nationalgeographic.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'US', 'media', 'National Geographic'),
  ('smithsonianmag.com', 'en', 'Culture', 'tier_3', 90, true, 'US', 'media', 'Smithsonian Magazine'),
  ('nytimes.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'US', 'media', 'New York Times'),
  ('washingtonpost.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'US', 'media', 'Washington Post'),
  ('latimes.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'US', 'media', 'Los Angeles Times'),
  ('wsj.com', 'en', 'Media - Business', 'tier_3', 90, true, 'US', 'media', 'Wall Street Journal'),
  ('npr.org', 'en', 'Media - National', 'tier_3', 90, true, 'US', 'media', 'National Public Radio'),
  ('pbs.org', 'en', 'Media - National', 'tier_3', 90, true, 'US', 'media', 'Public Broadcasting Service'),
  ('apnews.com', 'en', 'Media - National', 'tier_3', 90, true, 'US', 'media', 'Associated Press'),
  ('usatoday.com', 'en', 'Media - Quality Press', 'tier_3', 90, true, 'US', 'media', 'USA Today'),
  ('forbes.com', 'en', 'Media - Business', 'tier_3', 90, true, 'US', 'media', 'Forbes'),
  ('bloomberg.com', 'en', 'Media - Business', 'tier_3', 90, true, 'US', 'media', 'Bloomberg'),
  ('pewresearch.org', 'en', 'Research', 'tier_2', 95, true, 'US', 'nonprofit', 'Pew Research Center'),
  ('hbr.org', 'en', 'Media - Business', 'tier_3', 90, true, 'US', 'media', 'Harvard Business Review'),
  ('brookings.edu', 'en', 'Research', 'tier_2', 95, true, 'US', 'nonprofit', 'Brookings Institution'),
  ('mit.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Massachusetts Institute of Technology'),
  ('harvard.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Harvard University'),
  ('stanford.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Stanford University'),
  ('berkeley.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'UC Berkeley'),
  ('cornell.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Cornell University'),
  ('yale.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Yale University'),
  ('princeton.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Princeton University'),
  ('columbia.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Columbia University'),
  ('chicagobooth.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'University of Chicago Booth'),
  ('umich.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'University of Michigan'),
  ('utexas.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'University of Texas'),
  ('duke.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Duke University'),
  ('jhu.edu', 'en', 'Universities', 'tier_2', 95, true, 'US', 'academic', 'Johns Hopkins University'),
  ('mayo.edu', 'en', 'Health', 'tier_2', 95, true, 'US', 'academic', 'Mayo Clinic'),
  ('clevelandclinic.org', 'en', 'Health', 'tier_2', 95, true, 'US', 'medical', 'Cleveland Clinic'),
  ('kff.org', 'en', 'Health', 'tier_2', 95, true, 'US', 'nonprofit', 'Kaiser Family Foundation'),
  ('pubmed.ncbi.nlm.nih.gov', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'PubMed Research Database'),

  -- GERMANY
  ('bund.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'German Federal Government'),
  ('destatis.de', 'de', 'Statistics', 'tier_1', 100, true, 'DE', 'official', 'German Federal Statistics Office'),
  ('auswaertiges-amt.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'German Foreign Office'),
  ('bmwi.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'Federal Ministry for Economic Affairs'),
  ('bmel.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'Federal Ministry of Food and Agriculture'),
  ('bmg.bund.de', 'de', 'Health', 'tier_1', 100, true, 'DE', 'official', 'Federal Ministry of Health'),
  ('bmbf.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'Federal Ministry of Education and Research'),
  ('deutschland.de', 'de', 'Government', 'tier_1', 100, true, 'DE', 'official', 'Germany Official Portal'),
  ('dw.com', 'de', 'Media - National', 'tier_3', 90, true, 'DE', 'media', 'Deutsche Welle'),
  ('zeit.de', 'de', 'Media - Quality Press', 'tier_3', 90, true, 'DE', 'media', 'Die Zeit'),
  ('spiegel.de', 'de', 'Media - Quality Press', 'tier_3', 90, true, 'DE', 'media', 'Der Spiegel'),
  ('faz.net', 'de', 'Media - Quality Press', 'tier_3', 90, true, 'DE', 'media', 'Frankfurter Allgemeine Zeitung'),
  ('sueddeutsche.de', 'de', 'Media - Quality Press', 'tier_3', 90, true, 'DE', 'media', 'Süddeutsche Zeitung'),
  ('welt.de', 'de', 'Media - Quality Press', 'tier_3', 90, true, 'DE', 'media', 'Die Welt'),
  ('tagesschau.de', 'de', 'Media - National', 'tier_3', 90, true, 'DE', 'media', 'Tagesschau News'),
  ('zdf.de', 'de', 'Media - National', 'tier_3', 90, true, 'DE', 'media', 'ZDF Public Broadcasting'),
  ('br.de', 'de', 'Media - National', 'tier_3', 90, true, 'DE', 'media', 'Bayerischer Rundfunk'),
  ('uni-heidelberg.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'Heidelberg University'),
  ('uni-hamburg.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Hamburg'),
  ('hu-berlin.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'Humboldt University Berlin'),
  ('tu-berlin.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'Technical University Berlin'),
  ('uni-koeln.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Cologne'),
  ('uni-muenster.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Münster'),
  ('uni-freiburg.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Freiburg'),
  ('uni-leipzig.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'Leipzig University'),
  ('uni-frankfurt.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'Goethe University Frankfurt'),
  ('uni-bonn.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Bonn'),
  ('uni-giessen.de', 'de', 'Universities', 'tier_2', 95, true, 'DE', 'academic', 'University of Giessen'),
  ('maxplanckgesellschaft.de', 'de', 'Research', 'tier_2', 95, true, 'DE', 'academic', 'Max Planck Society'),
  ('fraunhofer.de', 'de', 'Research', 'tier_2', 95, true, 'DE', 'academic', 'Fraunhofer Society'),
  ('rki.de', 'de', 'Health', 'tier_1', 100, true, 'DE', 'official', 'Robert Koch Institute'),
  ('deutschebahn.com', 'de', 'Government', 'tier_3', 85, true, 'DE', 'official', 'German Railways'),
  ('deutschland-tourismus.de', 'de', 'Tourism', 'tier_3', 85, true, 'DE', 'tourism_board', 'Germany Tourism'),

  -- NETHERLANDS
  ('rijksoverheid.nl', 'nl', 'Government', 'tier_1', 100, true, 'NL', 'official', 'Dutch Government'),
  ('cbs.nl', 'nl', 'Statistics', 'tier_1', 100, true, 'NL', 'official', 'Statistics Netherlands'),
  ('npo.nl', 'nl', 'Media - National', 'tier_3', 90, true, 'NL', 'media', 'Dutch Public Broadcasting'),
  ('nos.nl', 'nl', 'Media - National', 'tier_3', 90, true, 'NL', 'media', 'NOS News'),
  ('nrc.nl', 'nl', 'Media - Quality Press', 'tier_3', 90, true, 'NL', 'media', 'NRC Handelsblad'),
  ('volkskrant.nl', 'nl', 'Media - Quality Press', 'tier_3', 90, true, 'NL', 'media', 'de Volkskrant'),
  ('trouw.nl', 'nl', 'Media - Quality Press', 'tier_3', 90, true, 'NL', 'media', 'Trouw'),
  ('parool.nl', 'nl', 'Media - Quality Press', 'tier_3', 90, true, 'NL', 'media', 'Het Parool'),
  ('uu.nl', 'nl', 'Universities', 'tier_2', 95, true, 'NL', 'academic', 'Utrecht University'),
  ('uva.nl', 'nl', 'Universities', 'tier_2', 95, true, 'NL', 'academic', 'University of Amsterdam'),
  ('vu.nl', 'nl', 'Universities', 'tier_2', 95, true, 'NL', 'academic', 'Vrije Universiteit Amsterdam'),
  ('eur.nl', 'nl', 'Universities', 'tier_2', 95, true, 'NL', 'academic', 'Erasmus University Rotterdam'),
  ('rug.nl', 'nl', 'Universities', 'tier_2', 95, true, 'NL', 'academic', 'University of Groningen'),
  ('radboudumc.nl', 'nl', 'Health', 'tier_2', 95, true, 'NL', 'academic', 'Radboud University Medical Center'),
  ('rivm.nl', 'nl', 'Health', 'tier_1', 100, true, 'NL', 'official', 'National Institute for Public Health'),
  ('amsterdam.nl', 'nl', 'Local Government', 'tier_3', 85, true, 'NL', 'municipal', 'Amsterdam City Council'),
  ('rotterdam.nl', 'nl', 'Local Government', 'tier_3', 85, true, 'NL', 'municipal', 'Rotterdam City Council'),
  ('denhaag.nl', 'nl', 'Local Government', 'tier_3', 85, true, 'NL', 'municipal', 'The Hague City Council'),
  ('utrecht.nl', 'nl', 'Local Government', 'tier_3', 85, true, 'NL', 'municipal', 'Utrecht City Council'),
  ('visitnetherlands.com', 'nl', 'Tourism', 'tier_3', 85, true, 'NL', 'tourism_board', 'Netherlands Tourism'),

  -- FRANCE
  ('gouvernement.fr', 'fr', 'Government', 'tier_1', 100, true, 'FR', 'official', 'French Government'),
  ('service-public.fr', 'fr', 'Government', 'tier_1', 100, true, 'FR', 'official', 'French Public Service Portal'),
  ('insee.fr', 'fr', 'Statistics', 'tier_1', 100, true, 'FR', 'official', 'French National Statistics'),
  ('france24.com', 'fr', 'Media - National', 'tier_3', 90, true, 'FR', 'media', 'France 24 News'),
  ('lemonde.fr', 'fr', 'Media - Quality Press', 'tier_3', 90, true, 'FR', 'media', 'Le Monde'),
  ('lefigaro.fr', 'fr', 'Media - Quality Press', 'tier_3', 90, true, 'FR', 'media', 'Le Figaro'),
  ('liberation.fr', 'fr', 'Media - Quality Press', 'tier_3', 90, true, 'FR', 'media', 'Libération'),
  ('francetvinfo.fr', 'fr', 'Media - National', 'tier_3', 90, true, 'FR', 'media', 'France TV Info'),
  ('santepubliquefrance.fr', 'fr', 'Health', 'tier_1', 100, true, 'FR', 'official', 'Public Health France'),
  ('cnrs.fr', 'fr', 'Research', 'tier_2', 95, true, 'FR', 'academic', 'French National Centre for Scientific Research'),
  ('gouv.fr', 'fr', 'Government', 'tier_1', 100, true, 'FR', 'official', 'French Government Portal'),
  ('paris.fr', 'fr', 'Local Government', 'tier_3', 85, true, 'FR', 'municipal', 'Paris City Council'),
  ('lyon.fr', 'fr', 'Local Government', 'tier_3', 85, true, 'FR', 'municipal', 'Lyon City Council'),
  ('marseille.fr', 'fr', 'Local Government', 'tier_3', 85, true, 'FR', 'municipal', 'Marseille City Council'),
  ('bordeaux.fr', 'fr', 'Local Government', 'tier_3', 85, true, 'FR', 'municipal', 'Bordeaux City Council'),
  ('toulouse.fr', 'fr', 'Local Government', 'tier_3', 85, true, 'FR', 'municipal', 'Toulouse City Council'),
  ('univ-paris.fr', 'fr', 'Universities', 'tier_2', 95, true, 'FR', 'academic', 'University of Paris'),
  ('univ-lyon.fr', 'fr', 'Universities', 'tier_2', 95, true, 'FR', 'academic', 'University of Lyon'),
  ('univ-marseille.fr', 'fr', 'Universities', 'tier_2', 95, true, 'FR', 'academic', 'Aix-Marseille University'),

  -- POLAND
  ('gov.pl', 'pl', 'Government', 'tier_1', 100, true, 'PL', 'official', 'Polish Government'),
  ('stat.gov.pl', 'pl', 'Statistics', 'tier_1', 100, true, 'PL', 'official', 'Polish Statistics Office'),
  ('niezalezna.pl', 'pl', 'Media - Quality Press', 'tier_3', 90, true, 'PL', 'media', 'Niezależna News'),
  ('tvp.pl', 'pl', 'Media - National', 'tier_3', 90, true, 'PL', 'media', 'Polish Public Television'),
  ('onet.pl', 'pl', 'Media - Quality Press', 'tier_3', 90, true, 'PL', 'media', 'Onet News Portal'),
  ('wp.pl', 'pl', 'Media - Quality Press', 'tier_3', 90, true, 'PL', 'media', 'Wirtualna Polska'),
  ('gazeta.pl', 'pl', 'Media - Quality Press', 'tier_3', 90, true, 'PL', 'media', 'Gazeta Wyborcza'),
  ('uj.edu.pl', 'pl', 'Universities', 'tier_2', 95, true, 'PL', 'academic', 'Jagiellonian University'),
  ('uw.edu.pl', 'pl', 'Universities', 'tier_2', 95, true, 'PL', 'academic', 'University of Warsaw'),
  ('pwr.edu.pl', 'pl', 'Universities', 'tier_2', 95, true, 'PL', 'academic', 'Wrocław University of Technology'),
  ('agh.edu.pl', 'pl', 'Universities', 'tier_2', 95, true, 'PL', 'academic', 'AGH University of Science and Technology'),
  ('visitpoland.com', 'pl', 'Tourism', 'tier_3', 85, true, 'PL', 'tourism_board', 'Poland Tourism'),

  -- SWEDEN
  ('sweden.se', 'sv', 'Government', 'tier_1', 100, true, 'SE', 'official', 'Swedish Government Portal'),
  ('scb.se', 'sv', 'Statistics', 'tier_1', 100, true, 'SE', 'official', 'Statistics Sweden'),
  ('svt.se', 'sv', 'Media - National', 'tier_3', 90, true, 'SE', 'media', 'Swedish Television'),
  ('dn.se', 'sv', 'Media - Quality Press', 'tier_3', 90, true, 'SE', 'media', 'Dagens Nyheter'),
  ('aftonbladet.se', 'sv', 'Media - Quality Press', 'tier_3', 90, true, 'SE', 'media', 'Aftonbladet'),
  ('kth.se', 'sv', 'Universities', 'tier_2', 95, true, 'SE', 'academic', 'KTH Royal Institute of Technology'),
  ('su.se', 'sv', 'Universities', 'tier_2', 95, true, 'SE', 'academic', 'Stockholm University'),
  ('lu.se', 'sv', 'Universities', 'tier_2', 95, true, 'SE', 'academic', 'Lund University'),
  ('visitstockholm.com', 'sv', 'Tourism', 'tier_3', 85, true, 'SE', 'tourism_board', 'Visit Stockholm'),

  -- NORWAY
  ('uio.no', 'no', 'Universities', 'tier_2', 95, true, 'NO', 'academic', 'University of Oslo'),
  ('uib.no', 'no', 'Universities', 'tier_2', 95, true, 'NO', 'academic', 'University of Bergen'),
  ('ssb.no', 'no', 'Statistics', 'tier_1', 100, true, 'NO', 'official', 'Statistics Norway'),
  ('nrk.no', 'no', 'Media - National', 'tier_3', 90, true, 'NO', 'media', 'Norwegian Broadcasting Corporation'),
  ('visitoslo.com', 'no', 'Tourism', 'tier_3', 85, true, 'NO', 'tourism_board', 'Visit Oslo'),

  -- DENMARK
  ('denmark.dk', 'da', 'Government', 'tier_1', 100, true, 'DK', 'official', 'Danish Government Portal'),
  ('dst.dk', 'da', 'Statistics', 'tier_1', 100, true, 'DK', 'official', 'Statistics Denmark'),
  ('dr.dk', 'da', 'Media - National', 'tier_3', 90, true, 'DK', 'media', 'Danish Broadcasting Corporation'),
  ('ku.dk', 'da', 'Universities', 'tier_2', 95, true, 'DK', 'academic', 'University of Copenhagen'),
  ('aarhus.dk', 'da', 'Local Government', 'tier_3', 85, true, 'DK', 'municipal', 'Aarhus Municipality'),
  ('visitcopenhagen.com', 'da', 'Tourism', 'tier_3', 85, true, 'DK', 'tourism_board', 'Visit Copenhagen'),

  -- GLOBAL
  ('who.int', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'World Health Organization'),
  ('un.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'United Nations'),
  ('unesco.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'UNESCO'),
  ('unicef.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'UNICEF'),
  ('worldbank.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'World Bank'),
  ('oecd.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'OECD'),
  ('imf.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'International Monetary Fund'),
  ('ilo.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'International Labour Organization'),
  ('fao.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'Food and Agriculture Organization'),
  ('wfp.org', 'global', 'International Org', 'tier_1', 100, true, 'GLOBAL', 'international', 'World Food Programme'),
  ('worldfoodtour.org', 'global', 'International Org', 'tier_3', 85, true, 'GLOBAL', 'nonprofit', 'World Food Tour'),
  ('worldwildlife.org', 'global', 'Environment', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'World Wildlife Fund'),
  ('iucn.org', 'global', 'Environment', 'tier_2', 95, true, 'GLOBAL', 'international', 'International Union for Conservation'),
  ('iucnredlist.org', 'global', 'Environment', 'tier_2', 95, true, 'GLOBAL', 'international', 'IUCN Red List'),
  ('climate.gov', 'global', 'Environment', 'tier_1', 100, true, 'GLOBAL', 'official', 'Climate.gov'),
  ('ipcc.ch', 'global', 'Environment', 'tier_1', 100, true, 'GLOBAL', 'international', 'Intergovernmental Panel on Climate Change'),
  ('globalcarbonproject.org', 'global', 'Environment', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'Global Carbon Project'),
  ('weforum.org', 'global', 'International Org', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'World Economic Forum'),
  ('amnesty.org', 'global', 'International Org', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'Amnesty International'),
  ('transparency.org', 'global', 'International Org', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'Transparency International'),
  ('worldeconomicforum.org', 'global', 'International Org', 'tier_2', 95, true, 'GLOBAL', 'nonprofit', 'World Economic Forum'),
  ('sciencedirect.com', 'global', 'Research', 'tier_2', 95, true, 'GLOBAL', 'academic', 'ScienceDirect Database'),
  ('europa.eu', 'eu', 'Government', 'tier_1', 100, true, 'EU', 'official', 'European Union'),
  ('ecb.europa.eu', 'eu', 'Government', 'tier_1', 100, true, 'EU', 'official', 'European Central Bank')

ON CONFLICT (domain) DO NOTHING;

INSERT INTO public.domain_usage_stats (domain, total_uses, last_used_at, created_at, updated_at)
SELECT ad.domain, 0, NOW(), NOW(), NOW()
FROM public.approved_domains ad
WHERE ad.is_allowed = true
  AND NOT EXISTS (SELECT 1 FROM public.domain_usage_stats dus WHERE dus.domain = ad.domain)
ON CONFLICT (domain) DO NOTHING;