-- Add columns for Q&A pairs 4-10 to emma_leads table
ALTER TABLE public.emma_leads 
ADD COLUMN IF NOT EXISTS question_4 TEXT,
ADD COLUMN IF NOT EXISTS answer_4 TEXT,
ADD COLUMN IF NOT EXISTS question_5 TEXT,
ADD COLUMN IF NOT EXISTS answer_5 TEXT,
ADD COLUMN IF NOT EXISTS question_6 TEXT,
ADD COLUMN IF NOT EXISTS answer_6 TEXT,
ADD COLUMN IF NOT EXISTS question_7 TEXT,
ADD COLUMN IF NOT EXISTS answer_7 TEXT,
ADD COLUMN IF NOT EXISTS question_8 TEXT,
ADD COLUMN IF NOT EXISTS answer_8 TEXT,
ADD COLUMN IF NOT EXISTS question_9 TEXT,
ADD COLUMN IF NOT EXISTS answer_9 TEXT,
ADD COLUMN IF NOT EXISTS question_10 TEXT,
ADD COLUMN IF NOT EXISTS answer_10 TEXT;